import Header from "@/components/molecules/Header";
import "./globals.css";
import type { Metadata } from "next";
import { NextAuthProvider } from "@/components/providers/NextAuthProvider";

export const metadata: Metadata = {
  title: "Yatai Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <NextAuthProvider>
        <body className={`flex flex-col min-h-screen bg-slate-100`}>
          <Header />
          <div className="flex-1">{children}</div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
